export const ja = {
  languages: {
    english: 'English',
    japanese: '日本',
  },
  languageSelectPopup: {
    select_language: '言語を選択する',
    confirm: '確認',
    selected: '選択済み',
  },
  emailPopup: {
    forgot_password: 'パスワードをお忘れですか',
    enter_email: '以下にメールアドレスを入力してください',
    email_text: 'Eメール',
    email_placeholder: 'Eメール',
    continue: '継続する',
  },
  otpPopup: {
    forgot_password: 'メールを検証する',
    enter_the_code: '受信したコードをメールアドレスに入力してください',
    received_the_code: 'コードを受け取っていませんか？',
    resend: '再送',
    complete: '完了',
  },
  newPasswordPopup: {
    new_password: '新しいパスワードを入力してください',
    password_text: 'パスワード',
    password_placeholder: 'パスワードを入力する',
    retype_password_text: 'パスワードをもう一度入力してください',
    retype_password_placeholder: 'パスワードを再入力してください',
    continue: '継続する',
  },
  loginScreen: {
    login: 'ログイン',
    email_text: 'メールアドレスを入力して',
    email_placeholder: 'メールアドレスを入力して',
    password_text: 'パスワードを入力する',
    password_placeholder: 'パスワードを入力する',
    forgot_password: 'パスワードをお忘れですか',
    forgot_password_modal: 'パスワードをお忘れですかモーダル',
    login_button: 'ログイン',
    have_an_account: 'アカウントをお持ちではありませんか？',
    register: '登録',
  },
  common: {
    loading: '読み込み中',
    login: 'ログイン',
    register: '登録',
    connectionError: '接続エラー',
  },
};
